//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerHabbitsMonitoring {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\AppData\\Local\\Telia\\PowerHabbitsMonitoring")]
        public string DLLDirectory {
            get {
                return ((string)(this["DLLDirectory"]));
            }
            set {
                this["DLLDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\AppData\\Local\\Telia\\PowerHabbitsMonitoring\\activity.txt")]
        public string InactiveTimeFile {
            get {
                return ((string)(this["InactiveTimeFile"]));
            }
            set {
                this["InactiveTimeFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\AppData\\Local\\Telia\\PowerHabbitsMonitoring\\StatusCache.txt")]
        public string StatusCache {
            get {
                return ((string)(this["StatusCache"]));
            }
            set {
                this["StatusCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws000webdev1.tcad.telia.se/PowerConsumptionMonitor/api/PowerConsumption")]
        public string ApiURL {
            get {
                return ((string)(this["ApiURL"]));
            }
            set {
                this["ApiURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\AppData\\Local\\Telia\\PowerHabbitsMonitoring\\ActivityTracker\\LastAc" +
            "tivityTracker.exe")]
        public string ActiveStatusExe {
            get {
                return ((string)(this["ActiveStatusExe"]));
            }
            set {
                this["ActiveStatusExe"] = value;
            }
        }
    }
}
